### ISSUE TITLE
EventID is always 0

### ISSUE THREAD

**Issue by t-smirnov** [NLog/NLog.Owin.Logging#16]
File: **NlogAdapter**
Method: **WriteCore**

Why I'm getting eventId = 0 when using WriteCore method?
You passing it into method as paramter, but never using it?

Thanks for response

**Comment by pysco68** [comment]
Hello Tim,

the signature of WriteCore() is actually defined in `Microsoft.Owin.Logging.ILogger`. That's why there's that "eventId" parameter. We're currently not using it as you stated, but if you can tell us a requirement or use case I'll look into it.

**Comment by pysco68** [comment]
Btw. I can't actually even find any information about the meaning of the `eventId` parameter (there's nothing written about it in the doc at least, and I found a couple of `ILogger` implementations not using it either or having funny _TODO_ comments for the matter).

**Comment by t-smirnov** [comment]
@pysco68 So, there is one way to do with

``` c#
public bool WriteCore(TraceEventType eventType, int eventId, object state, Exception exception, Func<object, Exception, string> formatter)
            {
                var logLevel = _getLogLevel(eventType);
                if (state == null)
                {
                    return _nlogger.IsEnabled(logLevel);
                }
                if (!_nlogger.IsEnabled(logLevel))
                {
                    return false;
                }

                var logEvent = NLog.LogEventInfo.Create(logLevel, _nlogger.Name, exception, _nlogger.Factory.DefaultCultureInfo, formatter(state, exception));
                logEvent.Properties[EvnetIdKey] = eventId;

                _nlogger.Log(logEvent);

                return true;
            }
```

Why you dont using `LogEventInfo`?

**Comment by pysco68** [comment]
That looks okay to me. Can you provide me some information about the _meaning_ of the eventId?
I'd like to write that down somewhere so that it is publicly known that it's actually there...

**Comment by t-smirnov** [comment]
@pysco68 EventId is identifier for logs written to Windows eventlog, providing easy monitoring etc.

**Comment by 304NotModified** [comment]
fixed in #17

**Comment by 304NotModified** [comment]
Will be released as 1.1. Thanks for reporting, @pysco68 thanks for fixing!

**Comment by 304NotModified** [comment]
https://www.nuget.org/packages/NLog.Owin.Logging/1.1.0

**Comment by t-smirnov** [comment]
@304NotModified nice, ty
